_exists(input(xplayer,mark(2,3)), 0).
_exists(input(oplayer,mark(1,2)), 0).
_exists(init(cell(3,1,b)), 0).
_exists(input(xplayer,mark(3,3)), 0).
_exists(domdomain(2,1), 0).
_exists(domdomain(5,50), 0).
_exists(init(cell(3,2,b)), 0).
_exists(init(cell(2,2,b)), 0).
_exists(timedomain(1), 0).
_exists(init(cell(1,2,b)), 0).
_exists(domdomain(2,3), 0).
_exists(init(control(xplayer)), 0).
_exists(domdomain(1,control), 0).
_exists(base(cell(1,3,b)), 0).
_exists(ldom(1), 0).
_exists(input(oplayer,mark(2,3)), 0).
_exists(base(cell(3,3,x)), 0).
_exists(init(cell(2,3,b)), 0).
_exists(input(xplayer,mark(2,1)), 0).
_exists(role(xplayer), 0).
_exists(base(cell(2,1,o)), 0).
_exists(input(oplayer,mark(1,1)), 0).
_exists(base(cell(2,3,b)), 0).
_exists(input(oplayer,mark(1,3)), 0).
_exists(init(cell(1,3,b)), 0).
_exists(base(cell(2,2,b)), 0).
_exists(ldom(4), 0).
_exists(input(xplayer,mark(3,2)), 0).
_exists(input(xplayer,mark(3,1)), 0).
_exists(base(cell(3,1,b)), 0).
_exists(base(cell(1,2,o)), 0).
_exists(base(cell(2,2,o)), 0).
_exists(input(xplayer,noop), 0).
_exists(base(cell(3,2,x)), 0).
_exists(input(oplayer,mark(3,2)), 0).
_exists(leq(0,0), 0).
_exists(base(cell(2,3,o)), 0).
_exists(base(cell(2,1,b)), 0).
_exists(domdomain(2,2), 0).
_exists(domdomain(4,xplayer), 0).
_exists(base(control(oplayer)), 0).
_exists(domdomain(4,oplayer), 0).
_exists(base(cell(1,3,x)), 0).
_exists(input(xplayer,mark(2,2)), 0).
_exists(base(cell(1,2,b)), 0).
_exists(input(oplayer,noop), 0).
_exists(index(2), 0).
_exists(base(cell(1,1,o)), 0).
_exists(domdomain(3,x), 0).
_exists(domdomain(3,b), 0).
_exists(domdomain(6,mark), 0).
_exists(domdomain(6,noop), 0).
_exists(base(cell(2,1,x)), 0).
_exists(input(xplayer,mark(1,1)), 0).
_exists(init(cell(2,1,b)), 0).
_exists(base(cell(3,1,o)), 0).
_exists(index(1), 0).
_exists(input(oplayer,mark(3,1)), 0).
_exists(domdomain(3,o), 0).
_exists(role(oplayer), 0).
_exists(base(cell(2,2,x)), 0).
_exists(init(cell(1,1,b)), 0).
_exists(base(cell(3,2,b)), 0).
_exists(base(control(xplayer)), 0).
_exists(input(oplayer,mark(3,3)), 0).
_exists(domdomain(1,cell), 0).
_exists(base(cell(1,2,x)), 0).
_exists(ldom(3), 0).
_exists(input(oplayer,mark(2,2)), 0).
_exists(input(oplayer,mark(2,1)), 0).
_exists(base(cell(3,3,b)), 0).
_exists(domdomain(5,0), 0).
_exists(domdomain(5,100), 0).
_exists(base(cell(3,3,o)), 0).
_exists(base(cell(1,1,b)), 0).
_exists(input(xplayer,mark(1,3)), 0).
_exists(index(3), 0).
_exists(base(cell(1,1,x)), 0).
_exists(base(cell(3,2,o)), 0).
_exists(init(cell(3,3,b)), 0).
_exists(base(cell(1,3,o)), 0).
_exists(base(cell(2,3,x)), 0).
_exists(input(xplayer,mark(1,2)), 0).
_exists(tdom(0), 0).
_exists(ldom(2), 0).
_exists(base(cell(3,1,x)), 0).
_forall(t1(T), 1) :- tdom(T).
_forall(s1(F), 1) :- base(F).
_forall(moveL1(M), 1) :- ldom(M).
_exists(true(control(oplayer)), 2).
_exists(does(xplayer,mark(3,2)), 2).
_exists(line(b), 2).
_exists(legal(xplayer,mark(2,3)), 2).
_exists(column(1,o), 2).
_exists(does(xplayer,mark(3,1)), 2).
_exists(next(cell(1,2,x)), 2).
_exists(does(xplayer,noop), 2).
_exists(row(3,b), 2).
_exists(true(cell(1,2,b)), 2).
_exists(next(cell(1,1,x)), 2).
_exists(true(cell(1,3,b)), 2).
_exists(next(control(xplayer)), 2).
_exists(legal(oplayer,noop), 2).
_exists(row(2,b), 2).
_exists(true(cell(2,3,b)), 2).
_exists(row(1,o), 2).
_exists(column(2,b), 2).
_exists(does(xplayer,mark(1,1)), 2).
_exists(terminal, 2).
_exists(true(control(xplayer)), 2).
_exists(row(2,o), 2).
_exists(legal(xplayer,mark(1,1)), 2).
_exists(legal(xplayer,mark(1,3)), 2).
_exists(does(xplayer,mark(2,2)), 2).
_exists(legal(oplayer,mark(2,1)), 2).
_exists(true(cell(1,3,o)), 2).
_exists(column(1,b), 2).
_exists(legal(oplayer,mark(1,3)), 2).
_exists(legal(xplayer,mark(1,2)), 2).
_exists(goal(oplayer,0), 2).
_exists(goal(xplayer,100), 2).
_exists(goal(oplayer,50), 2).
_exists(legal(oplayer,mark(3,3)), 2).
_exists(does(xplayer,mark(1,3)), 2).
_exists(true(cell(3,3,o)), 2).
_exists(line(x), 2).
_exists(true(cell(1,3,x)), 2).
_exists(legal(xplayer,mark(2,2)), 2).
_exists(next(cell(3,2,x)), 2).
_exists(does(xplayer,mark(1,2)), 2).
_exists(column(2,o), 2).
_exists(true(cell(3,1,b)), 2).
_exists(true(cell(3,3,x)), 2).
_exists(true(cell(1,2,o)), 2).
_exists(legal(oplayer,mark(2,2)), 2).
_exists(line(o), 2).
_exists(row(3,x), 2).
_exists(legal(xplayer,noop), 2).
_exists(next(cell(3,1,x)), 2).
_exists(true(cell(1,1,b)), 2).
_exists(legal(oplayer,mark(2,3)), 2).
_exists(next(cell(1,3,x)), 2).
_exists(column(3,x), 2).
_exists(goal(xplayer,50), 2).
_exists(true(cell(2,1,b)), 2).
_exists(open, 2).
_exists(diagonal(x), 2).
_exists(row(2,x), 2).
_exists(next(cell(2,3,x)), 2).
_exists(true(cell(2,2,b)), 2).
_exists(true(cell(3,2,o)), 2).
_exists(next(cell(3,3,x)), 2).
_exists(does(xplayer,mark(2,3)), 2).
_exists(true(cell(3,3,b)), 2).
_exists(true(cell(2,3,o)), 2).
_exists(true(cell(3,2,x)), 2).
_exists(row(1,b), 2).
_exists(diagonal(o), 2).
_exists(does(xplayer,mark(2,1)), 2).
_exists(column(1,x), 2).
_exists(true(cell(3,2,b)), 2).
_exists(legal(oplayer,mark(1,2)), 2).
_exists(column(2,x), 2).
_exists(legal(oplayer,mark(3,1)), 2).
_exists(true(cell(1,2,x)), 2).
_exists(column(3,o), 2).
_exists(legal(xplayer,mark(3,1)), 2).
_exists(goal(xplayer,0), 2).
_exists(true(cell(2,1,x)), 2).
_exists(true(cell(3,1,x)), 2).
_exists(legal(oplayer,mark(3,2)), 2).
_exists(next(cell(2,2,x)), 2).
_exists(row(3,o), 2).
_exists(true(cell(2,2,x)), 2).
_exists(true(cell(2,2,o)), 2).
_exists(legal(xplayer,mark(2,1)), 2).
_exists(legal(xplayer,mark(3,3)), 2).
_exists(true(cell(2,1,o)), 2).
_exists(next(cell(2,1,x)), 2).
_exists(true(cell(1,1,o)), 2).
_exists(diagonal(b), 2).
_exists(row(1,x), 2).
_exists(does(xplayer,mark(3,3)), 2).
_exists(column(3,b), 2).
_exists(legal(xplayer,mark(3,2)), 2).
_exists(true(cell(2,3,x)), 2).
_exists(next(control(oplayer)), 2).
_exists(goal(oplayer,100), 2).
_exists(legal(oplayer,mark(1,1)), 2).
_exists(true(cell(3,1,o)), 2).
_exists(true(cell(1,1,x)), 2).
_forall(moveL2(M), 3) :- ldom(M).
_exists(does(oplayer,mark(1,3)), 4).
_exists(next(cell(3,1,o)), 4).
_exists(next(cell(3,2,b)), 4).
_exists(next(cell(3,2,o)), 4).
_exists(next(cell(1,1,b)), 4).
_exists(does(oplayer,noop), 4).
_exists(does(oplayer,mark(3,1)), 4).
_exists(does(oplayer,mark(2,3)), 4).
_exists(does(oplayer,mark(1,1)), 4).
_exists(next(cell(1,3,b)), 4).
_exists(next(cell(1,2,o)), 4).
_exists(next(cell(3,3,o)), 4).
_exists(next(cell(2,2,o)), 4).
_exists(does(oplayer,mark(2,1)), 4).
_exists(does(oplayer,mark(3,3)), 4).
_exists(does(oplayer,mark(1,2)), 4).
_exists(next(cell(2,1,b)), 4).
_exists(next(cell(1,2,b)), 4).
_exists(next(cell(2,3,o)), 4).
_exists(next(cell(2,2,b)), 4).
_exists(next(cell(3,3,b)), 4).
_exists(does(oplayer,mark(3,2)), 4).
_exists(next(cell(2,1,o)), 4).
_exists(next(cell(1,1,o)), 4).
_exists(next(cell(2,3,b)), 4).
_exists(next(cell(1,3,o)), 4).
_exists(next(cell(3,1,b)), 4).
_exists(does(oplayer,mark(2,2)), 4).
_exists(neqa, 4).
_forall(t2(T), 5) :- tdom(T).
_exists(succtime, 6).
_exists(nsame(T), 6) :- tdom(T).
_exists(nopp(T), 6) :- tdom(T).
_exists(neqt, 6).
_forall(s2(F), 7) :- base(F).
_exists(neqs, 8).
_exists(neqsx, 8).
_depend(true2(F), t2(T)) :- base(F), tdom(T).
_depend(true2(F), s2(F)) :- base(F), base(F).
_depend(true2(F), moveL2(M)) :- base(F), ldom(M).
